[package]
name = "weave"
version = "0.1.3-alpha.0"
authors = ["Amr Hassan <amr.hassan@gmail.com>"]
edition = "2018"

[profile.release]
codegen-units = 1

[dependencies]
clap = "3.0.0-beta.2"
thiserror = "1.0.22"
sysinfo = "0.15.3"

[package.metadata.release]
disable-publish = true
